name: Merge

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: edbighead/python-flask-sample-app/app
        username: edbighead
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com